name: Update Dependencies

on:
  # schedule:
  #   - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: macos-15
    env:
      DEVELOPER_DIR: "/Applications/Xcode_16.4.app/Contents/Developer"
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get current datetime
        run: echo "DATE=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Run update_dependencies
        run: ./scripts/update_dependencies.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'auto: update llama.cpp dependency'
          title: '[auto] Update llama.cpp to latest version'
          body: |
            This PR updates the llama.cpp dependency to the latest version.
            
            - Automatically generated by the Update Dependencies workflow
            - Date: ${{ env.DATE }}
          branch: update-llama-dependency-${{ env.DATE }}
          draft: always-true
          base: main
          labels: |
            bot